extends Node
tool 

func wire_signals(connect:bool)->void :
	var scope = Profiler.scope(self, "wire_signals", [connect])

	var connections = connections()

	for source in connections:
		for from_signal in connections[source]:
			for target in connections[source][from_signal]:
				for to_method in connections[source][from_signal][target]:
					var method:String
					var bindings:Array

					if to_method is String:
						method = to_method
						bindings = []
					elif to_method is Array:
						assert (to_method.size() == 2)
						var array = to_method.duplicate()
						method = array.pop_front()
						bindings = array

					if connect:
						assert (source.has_signal(from_signal), "Error: No signal %s in object %s for connection to method %s in target %s" % [from_signal, source.get_name(), to_method, target.get_name()])
						assert (target.has_method(method), "Error while connecting signal %s from source %s: No method %s in target %s" % [from_signal, source.get_name(), method, target.get_name()])
						
						source.connect(from_signal, target, method, bindings)
					else :
						assert (source.has_signal(from_signal), "No signal %s in object %s" % [from_signal, source.get_name()])
						assert (target.has_method(method), "No method %s in object %s" % [to_method, target.get_name()])
						
						source.disconnect(from_signal, target, method)

func connections()->Dictionary:
	var scope = Profiler.scope(self, "connections", [])

	return {
		ActionManager:{
			"on_action_do":{
				WorkshopDirectory.workshop_root():["on_action_do"]
			}, 
			"on_action_undo":{
				WorkshopDirectory.workshop_root():["on_action_undo"]
			}
		}, 
		WorkshopDirectory.tool_mode():{
			"mode_changed":{
				WorkshopDirectory.workshop_root():["on_tool_mode_changed"], 
				WorkshopDirectory.coordinate_space():["on_tool_mode_changed"]
			}
		}, 
		WorkshopDirectory.collision_settings():{
			"resolve_collision_changed":{
				WorkshopDirectory.movement_proxy():["set_check_collision"]
			}
		}, 
		WorkshopDirectory.snap_settings():{
			"snap_move_step_changed":{
				WorkshopDirectory.resize_proxy():["set_min_size"]
			}
		}, 
		WorkshopDirectory.coordinate_space():{
			"changed":{
				WorkshopDirectory.widgets_remote_transform():["on_coordinate_space_changed"]
			}
		}, 
		WorkshopDirectory.resize_proxy():{
			"resized":{
				WorkshopDirectory.composite_object():["update_composite_data"], 
			}
		}, 
		WorkshopDirectory.mouse_plane_move_handler():{
			"drag_state_changed":{
				WorkshopDirectory.workshop_root():["on_drag_state_changed"]
			}
		}, 
		WorkshopDirectory.mouse_plane_rotate_handler():{
			"drag_state_changed":{
				WorkshopDirectory.workshop_root():["on_drag_state_changed"]
			}
		}, 
		WorkshopDirectory.hovered_node():{
			"hovered_node_changed":{
				WorkshopDirectory.group_manager():["hovered_node_changed"], 
				WorkshopDirectory.texture_property_overlay():["populate_node"], 
				WorkshopDirectory.eyedropper_manager():["update_hovered_color"]
			}, 
			"hover_normal_changed":{
				WorkshopDirectory.eyedropper_manager():["update_hovered_color"]
			}
		}, 
		WorkshopDirectory.selected_nodes():{
			"selected_nodes_changed":{
				WorkshopDirectory.workshop_root():["selection_manager_selected_nodes_changed"], 
				WorkshopDirectory.group_manager():["selected_nodes_changed"]
			}, 
			"node_selected":{
				WorkshopDirectory.scene_tree_control():["select_node"], 
				WorkshopDirectory.property_inspector_model():["add_target_node"], 
				WorkshopDirectory.composite_object():["add_composite_data"], 
			}, 
			"node_deselected":{
				WorkshopDirectory.scene_tree_control():["deselect_node"], 
				WorkshopDirectory.property_inspector_model():["remove_target_node"], 
				WorkshopDirectory.composite_object():["remove_composite_data"], 
			}, 
		}, 
		WorkshopDirectory.camera_focus_manager():{
			"focus_camera":{
				WorkshopDirectory.workshop_camera():[
					"focus_position"
				]
			}
		}, 
		WorkshopDirectory.hotkey_manager():{
			"hotkey_shape_next":{
				WorkshopDirectory.add_object_control():["shape_next"]
			}, 
			"hotkey_shape_prev":{
				WorkshopDirectory.add_object_control():["shape_prev"]
			}, 
			"hotkey_add_brick":{
				WorkshopDirectory.add_object_control():["add_object"]
			}, 
			"hotkey_camera_focus":{
				WorkshopDirectory.camera_focus_manager():["focus_camera_on_selection"]
			}, 
			"hotkey_camera_speed_down":{
				WorkshopDirectory.workshop_camera():["decrement_move_speed"]
			}, 
			"hotkey_camera_speed_up":{
				WorkshopDirectory.workshop_camera():["increment_move_speed"]
			}, 
			"hotkey_copy":{
				WorkshopDirectory.workshop_root():[["copy_selected_nodes", false]]
			}, 
			"hotkey_cut":{
				WorkshopDirectory.workshop_root():[["copy_selected_nodes", true]]
			}, 
			"hotkey_duplicate":{
				WorkshopDirectory.workshop_root():["duplicate_selected_nodes"]
			}, 
			"hotkey_delete":{
				WorkshopDirectory.workshop_root():["delete_selected_nodes"]
			}, 
			"hotkey_glue":{
				WorkshopDirectory.workshop_root():["glue_selection"]
			}, 
			"hotkey_group":{
				WorkshopDirectory.workshop_root():["group_selection"]
			}, 
			"hotkey_group_scope_in":{
				WorkshopDirectory.group_manager():["scope_in"]
			}, 
			"hotkey_group_scope_out":{
				WorkshopDirectory.group_manager():["scope_out"]
			}, 
			"hotkey_new_scene":{
				WorkshopDirectory.scene_manager():["new_scene"]
			}, 
			"hotkey_open_scene":{
				WorkshopDirectory.file_dialog():["load_scene"]
			}, 
			"hotkey_paste":{
				WorkshopDirectory.workshop_root():["paste"]
			}, 
			"hotkey_redo":{
				WorkshopDirectory.workshop_root():["redo"]
			}, 
			"hotkey_save_scene":{
				WorkshopDirectory.scene_manager():["save_scene"]
			}, 
			"hotkey_save_scene_as":{
				WorkshopDirectory.file_dialog():["save_scene_as"]
			}, 
			"hotkey_select_anchor":{
				WorkshopDirectory.tool_buttons():["tool_anchor"]
			}, 
			"hotkey_tool_move_drag":{
				WorkshopDirectory.tool_buttons():["tool_move_drag"]
			}, 
			"hotkey_tool_move":{
				WorkshopDirectory.tool_buttons():["tool_move_next"]
			}, 
			"hotkey_select_lock":{
				WorkshopDirectory.tool_buttons():["tool_lock"]
			}, 
			"hotkey_select_material":{
				WorkshopDirectory.tool_buttons():["tool_paint_material"]
			}, 
			"hotkey_select_paint":{
				WorkshopDirectory.tool_buttons():["tool_paint_color"]
			}, 
			"hotkey_tool_rotate_plane":{
				WorkshopDirectory.tool_buttons():["tool_rotate_plane"]
			}, 
			"hotkey_tool_resize":{
				WorkshopDirectory.tool_buttons():["tool_resize_next"]
			}, 
			"hotkey_select_surface":{
				WorkshopDirectory.tool_buttons():["tool_paint_surface"]
			}, 
			"hotkey_snap_to_face":{
				WorkshopDirectory.snap_to_face_manager():["snap_to_face"]
			}, 
			"hotkey_toggle_collision":{
				WorkshopDirectory.collision_settings():["toggle_resolve_collision"]
			}, 
			"hotkey_toggle_grid":{
				WorkshopDirectory.workshop_root():["toggle_world_grid_visible"]
			}, 
			"hotkey_toggle_box_select":{
				WorkshopDirectory.box_selector():["toggle_active"]
			}, 
			"hotkey_undo":{
				WorkshopDirectory.workshop_root():["undo"]
			}, 
			"hotkey_apply_color":{
				WorkshopDirectory.paint_color_manager():["paint_hovered_node"]
			}, 
			"hotkey_apply_surface":{
				WorkshopDirectory.paint_surface_manager():["paint_hovered_node"]
			}, 
			"hotkey_apply_material":{
				WorkshopDirectory.paint_material_manager():["paint_hovered_node"]
			}, 
			"hotkey_scope_in":{
				WorkshopDirectory.group_manager():["scope_in"], 
			}, 
			"hotkey_scope_out":{
				WorkshopDirectory.group_manager():["scope_out"]
			}, 
			"hotkey_flip":{
				WorkshopDirectory.workshop_root():["flip_selection"]
			}, 
			"hotkey_toggle_profiler_active":{
				Profiler:["toggle_active"]
			}, 
			"hotkey_toggle_profiler_clear_on_process":{
				Profiler:["toggle_clear_on_process"]
			}
		}, 
		WorkshopDirectory.paint_color_manager():{
			"active_color_changed":{
				WorkshopDirectory.tool_bar():["set_active_color"]
			}
		}, 
		WorkshopDirectory.paint_surface_manager():{
			"active_surface_changed":{
				WorkshopDirectory.tool_bar():["set_active_surface"]
			}
		}, 
		WorkshopDirectory.paint_material_manager():{
			"active_material_changed":{
				WorkshopDirectory.tool_bar():["set_active_material"]
			}
		}, 
		WorkshopDirectory.scene_manager():{
			"scene_load_started":{
				WorkshopDirectory.workshop_root():["scene_load_started"]
			}, 
			"scene_load_finished":{
				WorkshopDirectory.workshop_root():["scene_load_finished"], 
				WorkshopDirectory.backups_list():["on_scene_loaded"]
			}, 
			"show_save_as_dialog":{
				WorkshopDirectory.file_dialog():["save_scene_as"]
			}, 
			"scene_saved":{
				WorkshopDirectory.backups_list():["on_scene_saved"]
			}, 
		}, 
		WorkshopDirectory.scene_loader():{
			"populate_tree":{
				WorkshopDirectory.scene_manager():["populate_tree"]
			}, 
			"scene_load_failed":{
				WorkshopDirectory.scene_manager():["scene_load_failed"]
			}, 
			"scene_load_finished":{
				WorkshopDirectory.scene_manager():["scene_load_finished"], 
			}, 
			"scene_load_started":{
				WorkshopDirectory.scene_manager():["scene_load_started"]
			}, 
		}, 
		WorkshopDirectory.legacy_loader():{
			"populate_tree":{
				WorkshopDirectory.scene_manager():["populate_tree"]
			}, 
			"scene_load_finished":{
				WorkshopDirectory.scene_manager():["scene_load_finished"]
			}, 
			"scene_load_started":{
				WorkshopDirectory.scene_manager():["scene_load_started"]
			}, 
		}, 
		WorkshopDirectory.world_grid():{
			"visibility_changed_bool":{
				WorkshopDirectory.tool_bar():["set_grid_pressed"]
			}
		}, 
		WorkshopDirectory.workshop_camera():{
			"capture_mouse":{
				WorkshopDirectory.workshop_root():["capture_mouse"]
			}, 
			"move_speed_changed":{
				WorkshopDirectory.camera_widget():["set_move_speed"]
			}, 
			"release_mouse":{
				WorkshopDirectory.workshop_root():["release_mouse"]
			}, 
			"zoom_changed":{
				WorkshopDirectory.camera_widget():["set_zoom"]
			}
		}, 
		WorkshopDirectory.box_selector():{
			"active_changed":{
				WorkshopDirectory.workshop_root():["on_box_selector_active_changed"]
			}
		}, 
		WorkshopDirectory.bandbox_selector():{
			"node_deselected":{
				WorkshopDirectory.workshop_root():["band_box_node_deselected"]
			}, 
			"node_selected":{
				WorkshopDirectory.workshop_root():["band_box_node_selected"]
			}
		}, 
		WorkshopDirectory.tool_bar():{
			"copy":{
				WorkshopDirectory.workshop_root():[["copy_selected_nodes", false]]
			}, 
			"cut":{
				WorkshopDirectory.workshop_root():[["copy_selected_nodes", true]]
			}, 
			"glue":{
				WorkshopDirectory.workshop_root():["glue_selection"]
			}, 
			"group":{
				WorkshopDirectory.workshop_root():["group_selection"]
			}, 
			"hide_color_picker":{
				WorkshopDirectory.color_popup():["hide"]
			}, 
			"menu":{
				WorkshopDirectory.main_menu():["popup"]
			}, 
			"paste":{
				WorkshopDirectory.workshop_root():["paste"]
			}, 
			"redo":{
				WorkshopDirectory.workshop_root():["redo"]
			}, 
			"save":{
				WorkshopDirectory.scene_manager():["save_scene"]
			}, 
			"set_collision":{
				WorkshopDirectory.collision_settings():["set_resolve_collision"]
			}, 
			"set_grid":{
				WorkshopDirectory.world_grid():["set_visible"]
			}, 
			"set_box_select":{
				WorkshopDirectory.box_selector():["set_active"]
			}, 
			"set_picker_color":{
				WorkshopDirectory.color_picker_manager():["set_picker_color"]
			}, 
			"set_picker_connection":{
				WorkshopDirectory.color_picker_manager():["set_picker_connection"]
			}, 
			"show_color_picker":{
				WorkshopDirectory.color_picker_manager():["show_picker_at_control"]
			}, 
			"show_material_picker":{
				WorkshopDirectory.material_popup():["show_modal"]
			}, 
			"show_surface_picker":{
				WorkshopDirectory.surface_popup():["show_modal"]
			}, 
			"tool_move_drag":{
				WorkshopDirectory.tool_mode():["tool_move_drag"]
			}, 
			"tool_move_axis":{
				WorkshopDirectory.tool_mode():["tool_move_axis"]
			}, 
			"tool_move_plane":{
				WorkshopDirectory.tool_mode():["tool_move_plane"]
			}, 
			"tool_rotate_plane":{
				WorkshopDirectory.tool_mode():["tool_rotate_plane"]
			}, 
			"tool_resize_face":{
				WorkshopDirectory.tool_mode():["tool_resize_face"]
			}, 
			"tool_resize_edge":{
				WorkshopDirectory.tool_mode():["tool_resize_edge"]
			}, 
			"tool_resize_corner":{
				WorkshopDirectory.tool_mode():["tool_resize_corner"]
			}, 
			"tool_paint_color":{
				WorkshopDirectory.tool_mode():["tool_paint_color"]
			}, 
			"tool_paint_material":{
				WorkshopDirectory.tool_mode():["tool_paint_material"]
			}, 
			"tool_paint_surface":{
				WorkshopDirectory.tool_mode():["tool_paint_surface"]
			}, 
			"tool_anchor":{
				WorkshopDirectory.tool_mode():["tool_anchor"]
			}, 
			"tool_lock":{
				WorkshopDirectory.tool_mode():["tool_lock"]
			}, 
			"undo":{
				WorkshopDirectory.workshop_root():["undo"]
			}, 
		}, 
		WorkshopDirectory.edit_bar():{
			"set_coordinate_space":{
				WorkshopDirectory.coordinate_space():["set_coordinate_space"]
			}, 
			"set_playing":{
				WorkshopDirectory.workshop_root():["set_playing"]
			}, 
			"set_simulating":{
				WorkshopDirectory.workshop_root():["set_simulating"]
			}, 
			"set_snap_translation":{
				WorkshopDirectory.snap_settings():["set_snap_move"], 
			}, 
			"set_snap_translation_interval":{
				WorkshopDirectory.snap_settings():["set_snap_move_step"], 
				WorkshopDirectory.snap_to_face_manager():["set_snap_translation_interval"]
			}, 
			"set_snap_rotation":{
				WorkshopDirectory.snap_settings():["set_snap_rotate"], 
			}, 
			"set_snap_rotation_interval":{
				WorkshopDirectory.snap_settings():["set_snap_rotate_step"]
			}, 
		}, 
		WorkshopDirectory.menu_bar():{
			"button_index_pressed":{
				WorkshopDirectory.sidebar_tabs():["set_current_tab"]
			}
		}, 
		WorkshopDirectory.sidebar_tabs():{
			"visible_changed":{
				WorkshopDirectory.sidebar_dock():["set_visible"]
			}
		}, 
		WorkshopDirectory.scene_tree_control():{
			"node_selected":{
				WorkshopDirectory.selected_nodes():["add_selected_node"]
			}, 
			"node_deselected":{
				WorkshopDirectory.selected_nodes():["remove_selected_node"]
			}
		}, 
		WorkshopDirectory.scene_tree_search():{
			"text_changed":{
				WorkshopDirectory.workshop_root():["scene_tree_filter_changed"]
			}
		}, 
		WorkshopDirectory.viewport_control():{
			"viewport_input":{
				WorkshopDirectory.main_viewport():["unhandled_input"]
			}, 
			"viewport_resized":{
				WorkshopDirectory.viewport_compositor():["set_size"]
			}, 
			"focus_exited":{
				WorkshopDirectory.workshop_camera():["clear_input"]
			}
		}, 
		WorkshopDirectory.main_menu():{
			"show_graphics_options":{
				WorkshopDirectory.graphics_settings_popup():["popup"]
			}
		}, 
		WorkshopDirectory.file_dialog():{
			"import_brk":{
				WorkshopDirectory.scene_manager():["load_scene"]
			}, 
			"load_scene":{
				WorkshopDirectory.scene_manager():["load_scene"]
			}, 
			"save_scene_as":{
				WorkshopDirectory.scene_manager():["save_scene_as"]
			}
		}, 
		
		
		
		
		
		WorkshopDirectory.surface_popup():{
			"modal_closed":{
				WorkshopDirectory.tool_bar():[["set_surface_picker_pressed", false]]
			}
		}, 
		WorkshopDirectory.surface_picker():{
			"pressed_enum":{
				WorkshopDirectory.paint_surface_manager():["set_active_surface"]
			}
		}, 
		WorkshopDirectory.material_popup():{
			"modal_closed":{
				WorkshopDirectory.tool_bar():[["set_material_picker_pressed", false]]
			}, 
		}, 
		WorkshopDirectory.material_picker():{
			"pressed_enum":{
				WorkshopDirectory.paint_material_manager():["set_active_material"]
			}
		}, 
		GraphicsSettings.data:{
			"resolution_scale_factor_changed":{
				WorkshopDirectory.viewport_compositor():["update_viewport_size"]
			}
		}, 
		WorkshopDirectory.recent_files_list():{
			"load_scene":{
				WorkshopDirectory.scene_manager():["load_scene"]
			}, 
		}, 
		WorkshopDirectory.backups_list():{
			"load_scene":{
				WorkshopDirectory.scene_manager():["load_scene"]
			}, 
		}, 
		WorkshopDirectory.file_tab_header():{
			"close_pressed":{
				WorkshopDirectory.sidebar_tabs():[["set_tab", 0]]
			}
		}, 
		WorkshopDirectory.workspace_tab_header():{
			"close_pressed":{
				WorkshopDirectory.sidebar_tabs():[["set_tab", 0]]
			}
		}, 
		WorkshopDirectory.environment_tab_header():{
			"close_pressed":{
				WorkshopDirectory.sidebar_tabs():[["set_tab", 0]]
			}
		}
	}
